/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#F7F4EE",
        "on-background": "#181c1c",
        surface: "#f7faf8",
        "surface-dim": "#d7dbd9",
        "surface-bright": "#f7faf8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f3",
        "surface-container": "#ebefed",
        "surface-container-high": "#e5e9e7",
        "surface-container-highest": "#e0e3e1",
        "on-surface": "#181c1c",
        "on-surface-variant": "#3e4947",
        "inverse-surface": "#2d3130",
        "inverse-on-surface": "#eef1f0",
        outline: "#6e7977",
        "outline-variant": "#bdc9c6",
        "surface-tint": "#006a63",
        primary: "#005c55",
        "on-primary": "#ffffff",
        "primary-container": "#0f766e",
        "on-primary-container": "#a3faef",
        "inverse-primary": "#80d5cb",
        secondary: "#515f74",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e3fc",
        "on-secondary-container": "#57657a",
        "secondary-fixed": "#d5e3fc",
        tertiary: "#7f4025",
        "tertiary-container": "#9c573a",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "disclaimer-bg": "#F5E6B8",
        "disclaimer-text": "#370e00",
        "teal-button": "#0F766E",
      },
      borderRadius: {
        card: "16px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "20px",
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ['"Source Sans 3"', "sans-serif"],
        "body-md": ['"Source Sans 3"', "sans-serif"],
        "body-sm": ['"Source Sans 3"', "sans-serif"],
        "label-md": ['"Source Sans 3"', "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
